---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/dirien/backstage-demo
      targetRevision: HEAD
      path: backstage-resources
      directory:
        include: 'bs-*.yaml'
    - repoURL: https://github.com/my-silly-organisation/backstage.git
      targetRevision: main
      path: backstage-umbrella
      helm:
        valueFiles:
          - $values/backstage-resources/helm-values.yaml
    - repoURL: https://github.com/dirien/backstage-demo
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: backstage
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
